[CI-7842]: Implement add-on change for ti for Python
harness/lite-engine pull request #140
Opened 2023-05-01 18:47 UTC by happyhebaby

2023-05-02 07:12 UTC, rutvijmehta-harness commented on ti/instrumentation/python/pytest.go
> +		return strings.TrimSpace(
Define `"."` as constant and use it here

2023-05-02 07:12 UTC, rutvijmehta-harness commented on ti/instrumentation/python/pytest.go
> +	return fmt.Sprintf("python3 python_agent.py %s --test_harness %s --disable_static",
Define `"."` as constant and use it he

2023-05-02 07:12 UTC, rutvijmehta-harness commented on ti/instrumentation/python/pytest.go
> +	// Use only unique <package, class> tuples
```suggestion
	// Use only unique classes
```

2023-05-02 07:12 UTC, rutvijmehta-harness commented on ti/instrumentation/python/pytest.go
> +	return fmt.Sprintf("python3 python_agent.py %s --test_harness %s --disable_static",
Where is `testStr` when not ignoring instrumentation?

2023-05-02 07:12 UTC, rutvijmehta-harness commented on ti/instrumentation/python/unittest.go
> +	unittestCmd = "unittest"
Camel case everywhere

2023-05-02 07:12 UTC, rutvijmehta-harness commented on ti/instrumentation/python/unittest.go
> +	log.Infoln("NewUnitestRunner starting")
Typo

2023-05-02 07:12 UTC, rutvijmehta-harness commented on ti/instrumentation/python/unittest.go
> +// Copyright 2021 Harness Inc. All rights reserved.
All the same comments as `pytest.go`

2023-05-02 07:12 UTC, rutvijmehta-harness commented on ti/instrumentation/python/pytest.go
> +		return strings.TrimSpace(
Can you also look if it's possible to build the `agentArg` before hand and just add it here? For example: https://github.com/harness/lite-engine/blob/6d53379909358cdf3c9179e8ab64af5560771990/ti/instrumentation/java/maven.go#L57

2023-05-02 20:23 UTC, jamie-harness commented on ti/instrumentation/python/unittest.go
> +	return fmt.Sprintf("python3 python_agent.py %s --test_harness %s --disable_static",
This command should have a list of test as well. How does your agent run if a list of tests is passed in?

2023-05-03 17:02 UTC, happyhebaby commented on ti/instrumentation/python/helper.go
> +func GetPythonTests(testGlobs []string) ([]ti.RunnableTest, error) {
Changed, I couldn't test e2e to verify the original implementation.

2023-05-03 17:52 UTC, jamie-harness requested changes

2023-05-03 17:52 UTC, jamie-harness commented on ti/instrumentation/python/helper.go
> +func GetPythonTests(testGlobs []string) ([]ti.RunnableTest, error) {
As I mentioned in the Slack thread. Can you use the same logic as other languages and just put 
similar to this one
https://github.com/harness/harness-core/pull/47250/files#diff-428d42cf99a5feb27f8976c1e44817c8eec25c1614ea38517d16488cb4cc5229R31

2023-05-14 20:43 UTC, jamie-harness approved these changes

2023-05-14 20:44 UTC, merged

2023-05-14 21:04 UTC, rutvijmehta-harness commented on ti/instrumentation/python/unittest.go
> +	m.log.Infoln("Unittest GetCmd starting")
Log line doesn't add any benefit here. You can remove it.

2023-05-14 21:04 UTC, rutvijmehta-harness commented on ti/instrumentation/python/unittest.go
> +		m.log.Infoln(fmt.Sprintf("testCmd: %s", testCmd))
Log line doesn't add any benefit here. You can remove it.

2023-05-14 21:04 UTC, rutvijmehta-harness commented on ti/instrumentation/python/unittest.go
> +	// Use only unique <package, class> tuples
`// Use only unique classes`

2023-05-14 21:04 UTC, rutvijmehta-harness commented on ti/instrumentation/python/unittest.go
> +	m.log.Infoln(fmt.Sprintf("testCmd: %s", testCmd))
Log line doesn't add any benefit here. You can remove it.

2023-05-14 21:04 UTC, rutvijmehta-harness commented on ti/instrumentation/utils.go
> +		return fmt.Errorf("could not create directory: %s", err)
The errors are handled upstream. Please revert this.

2023-05-14 21:04 UTC, rutvijmehta-harness commented on ti/instrumentation/utils.go
> +		return fmt.Errorf("could not create request with context: %s", err)
The errors are handled upstream. Please revert this.

2023-05-14 21:04 UTC, rutvijmehta-harness commented on ti/instrumentation/utils.go
> +		return fmt.Errorf("could not make a request: %s", err)
The errors are handled upstream. Please revert this.

2023-05-14 21:04 UTC, rutvijmehta-harness commented on ti/instrumentation/utils.go
> +		return fmt.Errorf("could not copy: %s", err)
The errors are handled upstream. Please revert this.